### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by IftixorInTouch** [dantium/django-faicon#9]
Added field in my model:     category_icon = FAIconField()
And when I run python manage.py makemigrations this mistake is occurring:

Traceback (most recent call last):
  File "/Users/apple/Desktop/desctop/pycharm/pythonProject/ukr_mobile/manage.py", line 22, in <module>
    main()
  File "/Users/apple/Desktop/desctop/pycharm/pythonProject/ukr_mobile/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/apple/Desktop/desctop/pycharm/pythonProject/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/apple/Desktop/desctop/pycharm/pythonProject/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/Users/apple/Desktop/desctop/pycharm/pythonProject/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/apple/Desktop/desctop/pycharm/pythonProject/venv/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Users/apple/Desktop/desctop/pycharm/pythonProject/venv/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apple/Desktop/desctop/pycharm/pythonProject/venv/lib/python3.11/site-packages/faicon/models.py", line 43, in <module>
    ICON_LIST = get_icon_list()
                ^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/desctop/pycharm/pythonProject/venv/lib/python3.11/site-packages/faicon/models.py", line 23, in get_icon_list
    data_loaded = yaml.load(stream)
                  ^^^^^^^^^^^^^^^^^
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by shayneoneill** [comment]
Did you ever get an answer for this?
